version: "3.3"

volumes:
  api-code:
  db-data:
  api-node-modules:
  api-dist:

services:
  db:
    platform: linux/x86_64
    volumes:
      - "db-data:/var/lib/mysql"
  api:
    environment:
      - HOST=localhost
      - NODE_ENV=development
    volumes:
      - api-code:/app/src
      - api-node-modules:/app/src/node_modules
      - api-dist:/app/src/dist

# Set up Mutagen synchronization and forwarding.
x-mutagen:
  sync:
    defaults:
      stageMode: "neighboring"
      ignore:
        vcs: true
    code:
      alpha: "."
      beta: "volume://api-code"
      mode: "two-way-resolved"
      ignore:
        paths:
          - "README"
          - "Dockerfile"
          - "docker-compose*.yml"
      configurationBeta:
        permissions:
          defaultOwner: "id:9999" # app
          defaultGroup: "id:9999" # app
    nodemodules:
      alpha: "./node_modules"
      beta: "volume://api-node-modules"
      mode: "two-way-resolved"
      configurationBeta:
        permissions:
          defaultOwner: "id:9999" # app
          defaultGroup: "id:9999" # app
    dist:
      alpha: "./dist"
      beta: "volume://api-dist"
      mode: "two-way-resolved"
      configurationBeta:
        permissions:
          defaultOwner: "id:9999" # app
          defaultGroup: "id:9999" # app
